version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "permissions:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  n5api:
    build:
      context: .
      dockerfile: N5.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - elasticsearch
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ElasticUri=http://elasticsearch:9200
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

volumes:
  esdata1:
